name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_KEY }}
        shell: pwsh
        run: |
          ./build.ps1 -Path /tmp/samplemodule
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Publish-Module -Path /tmp/samplemodule -NuGetApiKey $env:NUGET_KEY -Forece -Verbose
